### ISSUE TITLE
real statistics for cyclegan

### ISSUE THREAD

**Issue by ash2703** [snap-research/CAT#10]
For training the teacher model do we need to calculate stats in both direction if my aim is AtoB only?

**Comment by alanspike** [comment]
Hey, stats are not necessary if you use other ways/metrics to choose the final model/checkpoint.

**Comment by youjin-c** [comment]
@alanspike, where can I set the other ways to choose the final model? which flag is it? cuz I see the real stat flags are always required, I don't know how not to use it.
```
train.py: error: the following arguments are required: --real_stat_A_path, --real_stat_B_path
```
