### ISSUE TITLE
自定义数据集

### ISSUE THREAD

**Issue by PL2584718785** [snap-research/CAT#14]
您好，大佬 麻烦请教下 可以用自己的数据集来训练压缩模型吗？  如果可以的话，文件.npz应该如何生成呢？ 谢谢您

**Comment by alanspike** [comment]
Thanks for your interests. This [file](https://github.com/snap-research/CAT/blob/main/get_real_stat.py) can be used for the calculation and here is some [information](https://github.com/snap-research/CAT#fidkid-computation) that might be helpful.
