### ISSUE TITLE
`get_real_stat.py` for custom dataset

### ISSUE THREAD

**Issue by youjin-c** [snap-research/CAT#17]
Hello,

I am testing CycleGAN as the readme documents.
It seems I need npz files for training, and when I see the command here
```
!python get_real_stat.py \
--dataroot database/horse2zebra \
--output_path real_stat/horse2zebra_A.npz \
--direction AtoB
```
and when I see the flag `--dataroot` it requires `trainA, trainB, valA, valB` and plus `train, val, etc` folders .
```
    parser.add_argument(
        '--dataroot',
        required=True,
        help=
        'path to images (should have subfolders trainA, trainB, valA, valB, train, val, etc)'
    )
```

I see CycleGAN requires usually 4 folders like `trainA, trainB, testA(valA), testB(valB)` but I am not sure what `train, val, etc` folders are for.
Could you explain how to set those folders? or is there a way to train without `.npz` files?

**Comment by deJQK** [comment]
Hi @youjinChung , thanks for your interest. trainA and trainB are for CycleGAN, train and val are for some other models (e.g. pix2pix). For those datasets part, please follow the usual practice as in CycleGAN and others.

**Comment by youjin-c** [comment]
Hello @deJQK,
Thanks for the reply, but I don't quite get it.
In my case, to train a CycleGAN, I already have `trainA, trainB, valA, valB` folders in my `database` folder.
However, when I run the `get_real_stat.py` file, it still requires `val` folder that doesn't exist.
my question is
1. I tried to change the name of either `valA` or `valB` and it seems worked (but I am not sure). Is that the right way to use it?
2. in that case, what `horse2zebra_A.npz` refers to? is it when using `valA` and `directionAtoB`? what are the right pairs? it is confusing what horse2zebra_A.npz means.

**Comment by deJQK** [comment]
Did you try this:
```
!python get_real_stat.py \
--dataroot database/horse2zebra \
--output_path real_stat/horse2zebra_A.npz \
--direction BtoA
```

**Comment by youjin-c** [comment]
@deJQK 
when I have `trainA, trainB, testA, testB, valA, valB` subfolders under `database/project_name`,
the command still returns
```
Traceback (most recent call last):
  File "get_real_stat.py", line 146, in <module>
    main(opt)
  File "get_real_stat.py", line 25, in main
    dataloader = create_dataloader(opt)
  File "/content/CAT/data/__init__.py", line 45, in create_dataloader
    dataloader = CustomDatasetDataLoader(opt, verbose)
  File "/content/CAT/data/__init__.py", line 79, in __init__
    self.dataset = dataset_class(opt)
  File "/content/CAT/data/aligned_dataset.py", line 24, in __init__
    self.AB_paths = sorted(make_dataset(self.dir_AB))  # get image paths
  File "/content/CAT/data/image_folder.py", line 58, in make_dataset
    dir), '%s is not a valid directory' % dir
AssertionError: database/project_name/val is not a valid directory
```

so when I go see the self.dir_AB is the error log,
`data/aligned_dataset.py`
```
def __init__(self, opt):
    ...
(line 22) self.dir_AB = os.path.join(opt.dataroot, opt.phase)  # get the image directory
```
and `opt.phase` in `data/__init__.py` file
```
def create_eval_dataloader(opt, direction=None):
    opt = copy.deepcopy(opt)
    # Set some evaluation options
    # opt.prepocess = 'resize_and_crop'
    opt.load_size = opt.crop_size
    opt.no_flip = True
    opt.serial_batches = True
    opt.batch_size = opt.eval_batch_size
    opt.phase = 'val'
```
`opt.phase` is set to `val` regardless to the `direction`
I guess that's the reason.

**Comment by youjin-c** [comment]
Okay, 
I found both of my test datasets, `horse2zebra,` and `ukiyoe2photo` are unaligned/unpaired datasets.
so I put `--dataset_mode unaligned\` flag on the command,
```
!python get_real_stat.py \
--dataroot database/ukiyoe2photo \
--dataset_mode unaligned\
--output_path real_stat/ukiyoe2photo_A.npz \
--direction BtoA
```

and it gives me out this error
```
dataset [UnalignedDataset] was created
/usr/local/lib/python3.7/dist-packages/torchvision/models/inception.py:77: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  ' due to scipy/scipy#11299), please set init_weights=True.', FutureWarning)
  0% 0/750 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "get_real_stat.py", line 146, in <module>
    main(opt)
  File "get_real_stat.py", line 38, in main
    tensor = data_i['image']
KeyError: 'image'
```

**Comment by alanspike** [comment]
May you please try the following?

```
python get_real_stat.py --dataroot database/ukiyoe2photo/valB --output_path real_stat/ukiyoe2photo_B.npz --direction AtoB --dataset_mode single

python get_real_stat.py --dataroot database/ukiyoe2photo/valA --output_path real_stat/ukiyoe2photo_A.npz --direction BtoA --dataset_mode single
```

**Comment by youjin-c** [comment]
@alanspike thanks for the reply.
those commands work.
only one concern is 
`
get_real_stat.py:121: UserWarning: Dataset mode [single] only supports direction BtoA. We will change the direction to BtoA.!
  warnings.warn('Dataset mode [single] only supports direction BtoA. '
`
I see this warning and am worried if the first command doesn't work as intended.

Below is the whole log.
```
get_real_stat.py:121: UserWarning: Dataset mode [single] only supports direction BtoA. We will change the direction to BtoA.!
  warnings.warn('Dataset mode [single] only supports direction BtoA. '
dataset [SingleDataset] was created
/usr/local/lib/python3.7/dist-packages/torchvision/models/inception.py:77: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  ' due to scipy/scipy#11299), please set init_weights=True.', FutureWarning)
100% 750/750 [00:02<00:00, 348.94it/s]
tcmalloc: large alloc 1179648000 bytes == 0xa639e000 @  0x7f339034c1e7 0x7f338dc5d0ce 0x7f338dcb3cf5 0x7f338dcb77e8 0x7f338dd4c841 0x59b076 0x515655 0x593dd7 0x5118f8 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f338ff49c87 0x5b621a
100% 24/24 [00:02<00:00, 10.61it/s]
dataset [SingleDataset] was created
/usr/local/lib/python3.7/dist-packages/torchvision/models/inception.py:77: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  ' due to scipy/scipy#11299), please set init_weights=True.', FutureWarning)
100% 262/262 [00:00<00:00, 361.18it/s]
100% 9/9 [00:00<00:00, 11.40it/s]
```

so should I temporally change the folder names (A<->B) for the direction `AtoB`?

**Comment by alanspike** [comment]
The direction actually doesn't matter. That's the legacy issue due to the script that we borrowed from [gan compression](https://github.com/mit-han-lab/gan-compression/issues/41).

**Comment by youjin-c** [comment]
@alanspike Gotcha. Thanks for the explanation!
So I can use the same commands for custom unpaired datasets, right?

**Comment by alanspike** [comment]
> So I can use the same commands for custom unpaired datasets, right?

No problem. Yes, it can be used for your own datasets.
