### ISSUE TITLE
Module Error in pix2pix distillation

### ISSUE THREAD

**Issue by Ashish-Abraham** [snap-research/CAT#22]
I have built a pix2pix model, fully functional using custom code. I downloaded this pre-trained one I made but, I am not able to compress it due to the following error.
```
RuntimeError: Error(s) in loading state_dict for InceptionGenerator:
Missing key(s) in state_dict: "down_sampling.1.weight", "down_sampling.2.weight", "down_sampling.2.bias", .....
Unexpected key(s) in state_dict: "final_conv.weight", "final_conv.bias", "encoders.0.conv.weight","encoders.1.bn.bias", "encoders.1.bn.running_mean",......
```
Just wanted to know if the distillation code works only for the architecture trained using the code in [models/pix2pix_model.py](https://github.com/snap-research/CAT/tree/main/models) and [trainer.py](https://github.com/snap-research/CAT/blob/main/trainer.py). The code I used to train the pix2pix GAN is [here](https://librecv.github.io/blog/gans/pytorch/2021/02/13/Pix2Pix-explained-with-code.html).

**Comment by Ashish-Abraham** [comment]
Also, I am using the code in tutorial branch.

**Comment by alanspike** [comment]
The pruning/distillation code is developed based on the IncResBlock introduced in the [paper](https://arxiv.org/pdf/2103.03467.pdf) (Page 3, Figure 2), which is different from the original pix2pix/CycleGAN generator.

**Comment by Ashish-Abraham** [comment]
So to work with CAT, I must implement existing GAN architectures with IncResBlocks, right?

**Comment by alanspike** [comment]
The repo includes the code to train a teacher model with IncResBlocks, or you could add other loss functions that you would like to use into the repo so that you don't need to implement existing GAN architectures with IncResBlocks.
