### ISSUE TITLE
distilling freezes with large dimension

### ISSUE THREAD

**Issue by youjin-c** [snap-research/CAT#23]
Hello,

Since my last CycleGAN model is too blurred, I brought a new dataset with 1024x1024.
Now I am testing the pipeline and found that distilling freezes with my specified dimension.
```
  --preprocess resize_and_crop \
  --load_size 1024 \
  --crop_size 1024,1024 \
```
It didn't work with `none preprocess` as well.
``` 
 --preprocess none
```
this is the last log that I can see. distilling doesn't proceed after this point.
```
...
features.8.res_ops.0.1.1.weight
features.8.res_ops.1.1.1.weight
features.8.res_ops.2.1.1.weight
features.8.dw_ops.0.0.1.weight
features.8.dw_ops.1.0.1.weight
features.8.dw_ops.2.0.1.weight
scale range: [0.9916747808456421, 1.014320731163025]
```

I've tested with some other options, like 
1. without those options(with default options) 
2. with the size of 500 
```
  --preprocess resize_and_crop \
  --load_size 500 \
  --crop_size 500,500 \
```
and distilling worked with those cases.

**_I wonder if it froze because it is too large or something I misunderstood with the sizing.
Also, I saw the options used 256x256 size as default, and other tutorial scripts used the same sizing, I wonder if I still need to go with this sizing with high-resolution face-changing filters.  I am training face filters that make people smile._**

Just in case, this is the whole option I used for distill.py
```
!python distill.py --dataroot database/face2smile \
  --dataset_mode unaligned \
  --distiller inception \
  --gan_mode lsgan \
  --log_dir logs/cycle_gan/face2smile/inception/student/2p6B \
  --restore_teacher_G_path logs/cycle_gan/face2smile/inception/teacher/checkpoints/best_A_net_G_A.pth \
  --restore_pretrained_G_path logs/cycle_gan/face2smile/inception/teacher/checkpoints/best_A_net_G_A.pth \
  --restore_D_path logs/cycle_gan/face2smile/inception/teacher/checkpoints/best_A_net_D_A.pth \
  --real_stat_path real_stat/face2smile_B.npz \
  --teacher_netG inception_9blocks --student_netG inception_9blocks \
  --pretrained_ngf 64 --teacher_ngf 64 --student_ngf 20 \
  --ndf 64 \
  --num_threads 80 \
  --eval_batch_size 4 \
  --batch_size 80 \
  --gpu_ids 0,1,2,3 \
  --norm_affine \
  --norm_affine_D \
  --channels_reduction_factor 6 \
  --kernel_sizes 1 3 5 \
  --lambda_distill 1.0 \
  --lambda_recon 5 \
  --prune_cin_lb 16 \
  --target_flops 2.6e9 \
  --distill_G_loss_type ka \
  --save_epoch_freq 1 \
  --save_latest_freq 500 \
  --norm_student batch \
  --padding_type_student zero \
  --norm_affine_student \
  --norm_track_running_stats_student \
  --preprocess resize_and_crop \
  --load_size 1024\
  --crop_size 500,500 \
  --nepochs 1 --nepochs_decay 0
```

**Comment by deJQK** [comment]
Hi @youjinChung, thanks again for your interest. Would you please check if the target FLOPs you provide is compatible with the new high resolution? For example, could you please use a larger target FLOPs, say the same as the current teacher (with the high resolution), or half of that to see if there is still this problem? Thanks.

**Comment by youjin-c** [comment]
hello @deJQK,

yes I checked the FLOP of the teacher is 696403165184 so changed the target FLOPs to `--target_flops 6.96e12 ` and it passed that point. (teacher model wasn't trained yet)
I needed the crop the model due to 'CUDA lack of memory issue' tho.
Thank you for your answer!!
