### ISSUE TITLE
Question on input dimensions of GKA

### ISSUE THREAD

**Issue by shiron8bit** [snap-research/CAT#4]
Hello, what is the optimal dimension of gka similarity? 
It seem that **.view(X.size(0),-1)** gives us n X hwc, but for batchwise/spatialwise similarity in the paper nhw X c is used.
Both variants seems reasonable (at least both gave 1 for similarity between tensor and itself), but their behaviour is very different.

**Comment by deJQK** [comment]
Hi @shiron8bit, thanks for your interest. Yes, you are right, the implementation here is using n X hwc, and this is because we find KA gives better results and finally we choose to use it to replace GKA. We will update the paper on arXiv asap to include this change.
