### ISSUE TITLE
AssertionError: Invalid device id

### ISSUE THREAD

**Issue by XUEXI-CL** [snap-research/CAT#7]
Hello, I encountered errors in model training. What should I do? Do you have any suggestions? Thank you very much！
“AssertionError: Invalid device id”

**Comment by alanspike** [comment]
Hey, I guess the gpu ids should be adjusted according to your computation resources. For example, changing the gpu ids [here](https://github.com/snap-research/CAT/blob/55bbe545b6fd0632d4171d021787671495244f79/scripts/cycle_gan/horse2zebra/train_inception_teacher.sh#L11).
